# Generated by Django 5.0.6 on 2024-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='student_course',
            field=models.CharField(max_length=100),
        ),
    ]
