# Generated by Django 5.0.6 on 2024-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_page_student_rollno_alter_page_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
