# Generated by Django 5.0.6 on 2024-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_page_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='student_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
