# Generated by Django 5.0.6 on 2024-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_page_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='student_Rollno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
